### PR TITLE
fix: Obsolete link URLs

### PR DESCRIPTION
**Pull request by hsinn0**
- Replaced a non-existing TAS 3.0 doc URL with a TAS 4.0 doc URL.
- Changed a Tanzu Net download URL to Broadcom Support Portal download URL.

[#187832330]

### CODE REVIEW

**Comment by anita-flegg** [comment]
CredHub is part of the TAS docs, so your assigned writer is Paul Spinrad.
I am the backup, though, so feel free to tag me if needed.

Note: The 3.0 link is broken because the TAS 3.0 docs have been archived. It's probably best to use doc version variables in the links. The current TAS release is 6.0.

**Comment by HenryBorys** [comment]
@anita-flegg Actually, this is mine. @hsinn0 Sorry for the delay. I've been on PTO till today and am catching up. I'll review this and publish.

**Comment by anita-flegg** [comment]
@HenryBorys -- Sorry, you're right! I was thinking about the CredHub repo that's used in the Tanzu Platform for Cloud Foundry docs.

**Comment by anita-flegg** [comment]
And in case we haven't been confusing enough, I am the backup for @HenryBorys docs too :)

**Pull request merged**
